#!/usr/bin/env python3
"""
seed_cycles.py — Create all 2026 bi-weekly delivery cycles for Sihha.

Usage:
    python3 seed_cycles.py

Set env vars before running:
    SEED_URL       (default: https://sihha-ops-hub-production.up.railway.app)
    SEED_PASSWORD  (your ADMIN_PASSWORD)

Idempotent: skips cycles whose delivery_date_start already exists in the DB.
"""

import os
import sys
import json
from datetime import date, timedelta
import urllib.request
import urllib.parse

BASE_URL  = os.environ.get('SEED_URL', 'https://sihha-ops-hub-production.up.railway.app')
PASSWORD  = os.environ.get('SEED_PASSWORD', '')

# ── Build cycle schedule ──────────────────────────────────────────────────────
def build_cycles():
    """
    Bi-weekly delivery on Saturday + Sunday.
    Last delivery: April 25-26, 2026.
    Next: May 9-10, then every 14 days through Dec 19-20.

    Order window:
      - Opens: 13 days before delivery Saturday (Monday of order week) at 08:00
      - Closes: 7 days before delivery Saturday (prev Saturday) at 23:59
    """
    cycles = []
    d = date(2026, 5, 9)   # first Saturday after April 25-26
    while d <= date(2026, 12, 31):
        sat = d
        sun = d + timedelta(days=1)
        order_close = sat - timedelta(days=7)   # Saturday before delivery
        order_open  = sat - timedelta(days=13)  # Monday 13 days before

        month_name = sat.strftime('%B')
        title = f'{month_name} {sat.day}–{sun.day}, 2026'

        cycles.append({
            'title':               title,
            'delivery_date_start': sat.isoformat(),
            'delivery_date_end':   sun.isoformat(),
            'request_open_at':     f'{order_open.isoformat()}T08:00:00',
            'request_close_at':    f'{order_close.isoformat()}T23:59:00',
            'status':              'draft',
            'notes':               'Auto-generated by seed_cycles.py',
        })
        d += timedelta(days=14)
    return cycles

# ── HTTP helpers ──────────────────────────────────────────────────────────────
def api(method, path, body=None, token=None):
    url = BASE_URL + path
    data = json.dumps(body).encode() if body else None
    headers = {'Content-Type': 'application/json'}
    if token:
        headers['Authorization'] = f'Bearer {token}'
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as e:
        raw = e.read()
        try:
            return e.code, json.loads(raw)
        except Exception:
            return e.code, {'_raw': raw.decode('utf-8', errors='replace')[:500]}

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    if not PASSWORD:
        print('ERROR: Set SEED_PASSWORD env var to your admin password.')
        print('  Example: SEED_PASSWORD=\'yourpassword\' python3 seed_cycles.py')
        sys.exit(1)

    print(f'Connecting to: {BASE_URL}')

    # Login
    status, resp = api('POST', '/api/auth/login', {'username': 'admin', 'password': PASSWORD})
    if status != 200:
        print(f'Login failed ({status}): {resp}')
        sys.exit(1)
    token = resp['token']
    print(f'Logged in as admin ✓\n')

    # Show ALL existing cycles so we can see what's actually in the DB
    _, existing = api('GET', '/api/delivery-cycles', token=token)
    print(f'Cycles currently in DB ({len(existing)} total):')
    for e in existing:
        print(f'  {e["delivery_date_start"]} [{e.get("status","?")}] {e["title"]}')

    # Only skip 2026 dates that already exist and appear in the API response
    existing_2026 = {c['delivery_date_start'] for c in existing if c['delivery_date_start'] >= '2026-01-01'}

    cycles = build_cycles()
    created = skipped = failed = 0

    print(f'\nAttempting to seed {len(cycles)} 2026 cycles...')
    for c in cycles:
        if c['delivery_date_start'] in existing_2026:
            print(f'  SKIP  {c["title"]:28}  (already visible in API)')
            skipped += 1
            continue

        c['status'] = 'upcoming'
        status_code, resp = api('POST', '/api/delivery-cycles', c, token=token)
        if status_code == 201:
            print(f'  ✓ OK  {c["title"]:28}')
            created += 1
        else:
            print(f'  ✗ ERR {c["title"]:28}  HTTP {status_code}: {resp}')
            failed += 1

    print(f'\nDone. Created: {created}  Skipped: {skipped}  Failed: {failed}')
    if failed:
        sys.exit(1)

if __name__ == '__main__':
    main()
